### PR TITLE
test for api_token_pass element before assigning new domain. Fix #71

### LINKED ISSUE #71: Widget gets logged-out when user visits a page other than home page
Steps to reproduce:
1. Sign in to codesy at the codesy home page
2. Use the widget - make a bid, make a claim, etc.
3. Go to a codesy page that isn't the home page - e.g., an admin page, or the claim detail page
4. Go back to an issue on GitHub

Expected results:
The codesy widget should be signed-in

Actual results:
The codesy widget is signed-out, and I have to refresh the codesy home page to make it sign back in

### PR DESCRIPTION
**Pull request by jdungan**
.../token

### CODE REVIEW

**Comment by groovecoder** [comment]
Looks like this is for https://github.com/codesy/chrome-extension/issues/71 ? You know you can put "fix #71" in the commit message to auto-close it? :wink:

**Comment by jdungan** [comment]
I meant to do that...

**Comment by groovecoder** [comment]
I think you have to put it in the commit message - i.e., not just the pull request title. But let's see if it works ... (tested on Firefox & Chrome)

**Comment by groovecoder** [comment]
Ah, I think it worked because my merge commit included the PR title in it.

**Comment by jdungan** [comment]
Thank god we avoided having to click on the closed button. :)

**Comment by groovecoder** [comment]
mouse

**Pull request merged**
